INSERT INTO `webbtek_webbtek`.`booksections` (`booksectionID`, `bookID`, `section`, `title`, `sortorder`) VALUES 
(NULL, 'wu1', '6',      'Teckenkodning och fonter',              135),
(NULL, 'wu1', '6.1',    'Ny rad som problem',                    136),
(NULL, 'wu1', '6.2',    'Äldre teckenkodningar',                 137),
(NULL, 'wu1', '6.3',    'Windows 1252',                          138),
(NULL, 'wu1', '6.4',    'Entititer',                             139),
(NULL, 'wu1', '6.5',    'Unicode',                               140),
(NULL, 'wu1', '6.5.1',  'Glyfer',                                141),
(NULL, 'wu1', '6.5.2',  'Tecken och teckentabeller',             142),
(NULL, 'wu1', '6.5.3',  'Teckenkodning',                         143),
(NULL, 'wu1', '6.5.4',  'UTF-8',                                 144),
(NULL, 'wu1', '6.5.5',  'Hur fungerar UTF-8',                    145),
(NULL, 'wu1', '6.6',    'URL-kodade tecken',                     146),
(NULL, 'wu1', '6.7',    'Base64-kodning',                        147),
(NULL, 'wu1', '6.8',    'Språkförbistring mellan Unicode och http/html', 148),
(NULL, 'wu1', '6.9',    'Hur ange teckenkodning',                149),
(NULL, 'wu1', '6.9.1',  'Teckenkodning kan anges med ett http-huvud', 150),
(NULL, 'wu1', '6.9.2',  'Teckenkodning kan anges med elementet <meta>', 151),
(NULL, 'wu1', '6.9.3',  'Teckenkodning kan - men bör inte - anges med BOM', 152),
(NULL, 'wu1', '6.9.4',  'Teckenkodning kan anges i XML-deklarationen', 153),
(NULL, 'wu1', '6.9.5',  'Lita (inte) på att webbläsarna gissar rätt', 154),
(NULL, 'wu1', '6.10',   'Mer om MIME',                           155),
(NULL, 'wu1', '6.11',   'Fonter',                                156),
(NULL, 'wu1', '6.11.1', 'Nedladdningsbara typsnitt',             157),
(NULL, 'wu1', '6.11.2', 'Font-stackar',                          158),
(NULL, 'wu1', '6.12',   'Stil (CSS)',                            159),
(NULL, 'wu1', '6.13',   'Summa',                                 160),
(NULL, 'wu1', '7',      'HTML historik och teori',               161),
(NULL, 'wu1', '7.1',    'HTML under pionjärtiden',               162),
(NULL, 'wu1', '7.2',    'Utveckling under browserkriget',        163),
(NULL, 'wu1', '7.3',    'CSS föds och HTML 4 skapas',            164),
(NULL, 'wu1', '7.4',    'XML',                                   165),
(NULL, 'wu1', '7.5',    'XHTML',                                 166),
(NULL, 'wu1', '7.6',    'Standardiseringsprocessen',             167),
(NULL, 'wu1', '7.7',    'Äkta XHTML',                            168),
(NULL, 'wu1', '7.8',    'HTML5',                                 169),
(NULL, 'wu1', '7.9',    'Versionslös HTML',                      170),
(NULL, 'wu1', '7.10',   'Kompatibiltetslägen',                   171),
(NULL, 'wu1', '7.10.1', 'Doctype-switching',                     172),
(NULL, 'wu1', '7.10.2', 'CSS-hack',                              173),
(NULL, 'wu1', '7.10.3', 'Internet Explorers olika lägen',        174),
(NULL, 'wu1', '7.11',   'HTML-element',                          175),
(NULL, 'wu1', '7.11.1', '<em>',                                  176),
(NULL, 'wu1', '7.11.2', '<strong>',                              177),
(NULL, 'wu1', '7.11.3', '<i>',                                   178),
(NULL, 'wu1', '7.11.4', '<b>',                                   179),
(NULL, 'wu1', '7.11.5', '<abbr>',                                180),
(NULL, 'wu1', '7.11.6', '<time>',                                181),
(NULL, 'wu1', '7.12',   'Förkortade attribut',                   182),
(NULL, 'wu1', '7.13',   'Element utan sluttagg',                 183),
(NULL, 'wu1', '7.13.1', '<base />',                              184),
(NULL, 'wu1', '7.13.2', '<br />',                                185),
(NULL, 'wu1', '7.13.3', '<hr />',                                186),
(NULL, 'wu1', '7.14',   'Element som skapas av sig självt (implicita element)', 187),
(NULL, 'wu1', '7.15',   'Element som stängs av andra element (implicita stängning)', 188),
(NULL, 'wu1', '7.16',   'HTML5:s innehållsmodell',               189),
(NULL, 'wu1', '8',      'CSS historik och teori',                190),
(NULL, 'wu1', '8.1',    'Bakgrund och versioner',                191),
(NULL, 'wu1', '8.1.1',  'CSS 1.0',                               192),
(NULL, 'wu1', '8.1.2',  'CSS 2.0 och 2.1',                       193),
(NULL, 'wu1', '8.1.3',  'Genombrottet för CSS-layout',           194),
(NULL, 'wu1', '8.1.4',  'Prefix och runda hörn',                 195),
(NULL, 'wu1', '8.1.5',  'Prefix och färgtoningar',               196),
(NULL, 'wu1', '8.1.6',  'CSS 3',                                 197),
(NULL, 'wu1', '8.2',    'Hur infoga CSS',                        198),
(NULL, 'wu1', '8.2.1',  'Med attributet style (inline CSS)',     199),
(NULL, 'wu1', '8.2.2',  'Elementet <style>',                     200),
(NULL, 'wu1', '8.2.3',  'Externt via elementet <link>',          201),
(NULL, 'wu1', '8.3',    'Måttenheter',                           202),
(NULL, 'wu1', '8.3.1',  'Procent',                               203),
(NULL, 'wu1', '8.3.2',  'Pixlar (px)',                           204),
(NULL, 'wu1', '8.3.3',  'Andra absoluta mått',                   205),
(NULL, 'wu1', '8.3.4',  'Mått relativa textstorleken',           206),
(NULL, 'wu1', '8.3.5',  'Mått relativa dokumentfönstret (experimentella måttenheter)', 207),
(NULL, 'wu1', '8.3.6',  'Tidsenheter och vinklar',               208),
(NULL, 'wu1', '8.4',    'Mer om selektorer',                     209),
(NULL, 'wu1', '8.4.1',  'Gruppselektorer',                       210),
(NULL, 'wu1', '8.4.2',  'Pseudoklasser',                         211),
(NULL, 'wu1', '8.4.3',  'Selektorer för länkar',                 212),
(NULL, 'wu1', '8.4.4',  'Strukturella pseudoklasser',            213),
(NULL, 'wu1', '8.4.5',  'Pseudoelement',                         214),
(NULL, 'wu1', '8.4.6',  'Attributselektorer',                    215),
(NULL, 'wu1', '8.5',    'Specificitet',                          216),
(NULL, 'wu1', '8.6',    '(Not so) !important',                   217),
(NULL, 'wu1', '8.7',    'Arv (inheritence)',                     218),
(NULL, 'wu1', '8.8',    'Kaskaden',                              219),
(NULL, 'wu1', '8.9',    'Att resetta eller inte resetta - det är frågan?', 220),
(NULL, 'wu1', '8.10',   'Kortformer (Shorthands)',               221),
(NULL, 'wu1', '8.11',   '@media',                                222),
(NULL, 'wu1', '9',      'Färger och bilder',                     223),
(NULL, 'wu1', '9.1',    'Färgsystem',                            224),
(NULL, 'wu1', '9.2',    'Färgkoder',                             225),
(NULL, 'wu1', '9.2.1',  'Namngivna färger',                      226),
(NULL, 'wu1', '9.2.2',  'Hexadecimala koder',                    227),
(NULL, 'wu1', '9.2.3',  'rgb() och rgba()',                      228),
(NULL, 'wu1', '9.2.4',  'hsl() och hsla()',                      229),
(NULL, 'wu1', '9.2.5',  'Jämförelsetabell mellan olika sätt att ange färg', 230),
(NULL, 'wu1', '9.3',    'Bilder',                                231),
(NULL, 'wu1', '9.3.1',  'Meningsbärande bilder',                 232),
(NULL, 'wu1', '9.3.2',  'Dekorativa blder',                      233),
(NULL, 'wu1', '9.3.3',  'Kortform (shorthand) för bakgrunder',   234),
(NULL, 'wu1', '9.4',    'Bildformat',                            235),
(NULL, 'wu1', '9.4.1',  'Gif',                                   236),
(NULL, 'wu1', '9.4.2',  'PNG',                                   237),
(NULL, 'wu1', '9.4.3',  'JPEG',                                  238),
(NULL, 'wu1', '9.4.4',  'SVG',                                   239),
(NULL, 'wu1', '9.4.5',  'MathML',                                240),
(NULL, 'wu1', '9.4.6',  'Canvas (2D) och WebGL (3D)',            241),
(NULL, 'wu1', '9.4.7',  'Jämförelsetabell mellan SVG, Canvas och WebGL', 242),
(NULL, 'wu1', '9.4.8',  'Andra bildformat',                      243),
(NULL, 'wu1', '9.5',    'Bildoptimering',                        244),
(NULL, 'wu1', '10',     'Boxar och sektioner',                   245),
(NULL, 'wu1', '10.1',   'CSS-egenskapen display',                246),
(NULL, 'wu1', '10.2',   'Boxmodellen i CSS',                     247),
(NULL, 'wu1', '10.2.1', 'Boxmodellen i CSS 2.1 och default i CSS 3', 248),
(NULL, 'wu1', '10.2.2', 'Boxmodellen i quirks mode',             249),
(NULL, 'wu1', '10.2.3', 'Boxmodellerna i CSS 3',                 250),
(NULL, 'wu1', '10.2.4', 'Outline kontra border',                 251),
(NULL, 'wu1', '10.3',   'Placering av boxar',                    252),
(NULL, 'wu1', '10.3.1', 'Position: static',                      253),
(NULL, 'wu1', '10.3.2', 'Position: absolute',                    254),
(NULL, 'wu1', '10.3.3', 'Position: fixed',                       255),
(NULL, 'wu1', '10.3.4', 'Position: relative',                    256),
(NULL, 'wu1', '10.3.5', 'CSS-transformering',                    257),
(NULL, 'wu1', '10.4',   'Outlines och HTML5-sektioner',          258),
(NULL, 'wu1', '10.5',   'Element som skapar sektioner (Sectioning elements)', 259),
(NULL, 'wu1', '10.5.1', '<section>',                             260),
(NULL, 'wu1', '10.5.2', '<article>',                             261),
(NULL, 'wu1', '10.5.3', '<nav>',                                 262),
(NULL, 'wu1', '10.5.4', '<aside>',                               263)
;
